apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  _;
          root   /usr/share/nginx/html;
          index  index.html index.htm;

          location /europe {
              alias /usr/share/nginx/html/;
              index  index.html index.html;
          }
          location /asia {
              alias /usr/share/nginx/html/;
              index  index.html index.html;
          }
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: world
